[tool.poetry]
name = "anqa-events"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"
packages = [
    { include = "anqa" }
]


[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
