name: Release anqa-core

on:
  push:
    branches:
      - release/*
    paths: packages/anqa-core/_version.py

jobs:
  release-anqa-core:
    uses:
      ./.github/workflows/release.yml
    with:
      working-directory: packages/anqa-core
    secrets: inherit